{% set name = "viewstack" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/viewstack-{{ version }}.tar.gz
  sha256: 6b20010c7a9c20906ff751bdccbdd38fef35983e4f752ea31eca1a24042920bd

build:
  entry_points:
    - viewstack = viewstack.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - viewable

test:
  imports:
    - viewstack
  commands:
    - pip check
    - viewstack --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/viewstack
  summary: Stack-based navigation for Python desktop apps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
